export const GET_TECHNOLOGIES = "GET_TECHNOLOGIES";
export const GET_TECHNOLOGY = "GET_TECHNOLOGY";
export const UPDATE_TECHNOLOGY = "UPDATE_TECHNOLOGY";
export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY";